### PR TITLE
Support for styles and roles

### PR DESCRIPTION
**Pull request by alexobviously**
* Added support for styles and roles. This feature allows users to leverage more advanced parameters in the Azure TTS API, allowing, for example, generating 'cheerful' or 'sad' TTS audio.
  * `VoiceModel` includes `styles` and `roles` fields, corresponding to `StyleList` and `RolePlayList` in the API response, respectively.
  * `TtsParams` accepts optional `style`, `styleDegree` and `role` parameters.
* Upgraded to Dart 3, and upgraded all dependencies (I did try to avoid this to keep this PR focused, but `build_runner` was having conflicts and it needs to be done eventually anyway).
* Created a more complex example script with some params, and writing audio out (`example/lib/example.dart`). The existing example is still there under `main.dart`. Feel free to rename.

I suggest making this part of `0.2.0` because the SDK constraint has changed.

### CODE REVIEW

**Comment by yashpalzala** [comment]
The ssml with style parameter does not contain `mstts:express-as` element. Thus, I doubt if style will work.

**Comment by yashpalzala** [comment]
> 
I tried your ssml it does work. 
Also I was able to make this current ssml work with `mstts` tag and for your understanding in future this is how we can use `mstts` tag in current ssml, 
`"<speak version='1.0' "
        "xmlns='http://www.w3.org/2001/10/synthesis' "
        "xmlns:mstts='https://www.w3.org/2001/mstts' "
        "xml:lang='${voice.locale}'>"
        "<voice xml:lang='${voice.locale}' "
        "xml:gender='${voice.gender}' "
        "name='${voice.shortName}'>"
        "<prosody rate='$speed'>"
        "<mstts:express-as style='$style' styledegree='$styleDegree'>"
        "$text"
        "<\/mstts:express-as>"
        "<\/prosody><\/voice><\/speak>"` .
Also you can add `styleDegree` in your current ssml it definitely helps in intensifying the style. 
If you can't, let me know I'll add that for you. 😄

**Comment by alexobviously** [comment]
Oh nice thanks, I didn't know about style degree!
I added a commit, it's supported now. Try something like `example.dart -s excited -d 0.01,0.5,1.0,2.0`, it's pretty cool, and I definitely have a use for this in an app.

r.e. `xml:` vs `mstts`, I think I personally prefer the xml attribute method. In my opinion, it's a bit more concise and easier to read, and it has the same effect anyway. But I'll leave it up to @ghuyfel, I don't mind that much.

**Comment by yashpalzala** [comment]
Yes will surely try. 

Actually I also had a use for style and styleDegree and I was just about to raise PR for both this parameters but then I saw your PR so then I didn't but I had completed the code and all, What a co-incidence! 

And yeah regarding `xml:` vs `mstts` I don't mind any of them as long as it works.

**Comment by ddikman** [comment]
It would be great to get this merged

**Comment by ghuyfel** [comment]
Hi David,  I have been very busy recently,   I will have a look at the PR over the weekend. Thanks for the support

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ddikman** [comment]
@ghuyfel no worries, sorry to rush :) I ended up doing a tiny version of this directly in our code base instead, so don't feel any pressure!

**Comment by ghuyfel** [comment]
Thanks a lot @alexobviously, well done

**Pull request merged**
